### ISSUE TITLE
Restore the password

### ISSUE THREAD

**Issue by pavlyukpetr** [turtlecoin/turtle-wallet#41]
Hello, how can I restore the password to the gui wallet?

**Comment by BebopTC** [comment]
Hi @pavlyukpetr. I see you've opened a couple of issues with support related questions. The github issues feature is primarily for bug reports, dev discussion and feature requests,

You cannot restore a password in then traditional sense. If you have lost or forgotten the password to your wallet container file, you will have to reimport the wallet using the private view key and private spend key. If you need help/assistance ,please visit http://discord.turtlecoin.lol 

Thanks!
