### ISSUE TITLE
Deamon connection failed

### ISSUE THREAD

**Issue by pavlyukpetr** [turtlecoin/turtle-wallet#42]
Hello, when I try to open my wallet or create a new one via gui I see the message "Deamon connection failed" and after the programm is closed.
What is the problem with it?
![clip2net_180305110250](https://user-images.githubusercontent.com/11602610/36966293-faa03bf6-2064-11e8-8e23-64830c6a1047.png)

**Comment by obigaff** [comment]
Can you scroll down in the same folder as your wallet.exe and see what's in the log?

Head over to the discord in the #help chat https://discord.gg/db5Dqx

**Comment by pavlyukpetr** [comment]
On the log I see the message Stopped.

**Comment by CaptainMeatloaf** [comment]
This is the wrong wallet software for this bug report. You are looking for: https://github.com/turtlecoin/desktop-xamarin

In addition, questions like this are more suited to the #help channel on the discord server.
