### ISSUE TITLE
Opening and closing a walletd process alongside the wallet

### ISSUE THREAD

**Issue by CaptainMeatloaf** [turtlecoin/turtle-wallet#8]
This wallet interacts with walletd for it's features. Right now, it requires the user to start up their own instance of walletd.

We need to detect if there is a walletd process already running and if there isn't, start one up as a child process (and close when the wallet is closed).

We also need to track the syncing state of walletd so that users are aware of what is going on and why their transactions aren't appearing if they are opening the wallet for the first time on a particular machine, or their machine is behind and still syncing.

It may be wise to pair this with #10 so it works seamlessly.

Feedback is welcome on this issue as I probably missed a few things here.

**Comment by gill3m** [comment]
Hi,
I am currently testing this on Ubuntu 16.04
1) walletd still expects the -w walletname and -p password flags.  These should be irrelevant when starting from within the GUI. Am i using an old version of walletd, my version is v2.1.2.1251 
2) after startup the GUI shows 0 balance on my wallet even though i sent it approx 8K in several transactions and checked the balance with simplewallet before using the GUI.
3) At the moment i am starting walletd from the current directory. We dont really have an alternative on Linux
4) When stopping the walletd i get an error in the log file and also on the console ERROR   WalletGreen is already stopped

**Comment by RocksteadyTC** [comment]
I will test this when I get done at the office today. Thank you for taking time to put together the details. Which TurtleCoin version are you using for this test? v0.2.2 is latest release.

**Comment by CaptainMeatloaf** [comment]
1, 2, and 4 - try updating to the latest walletd.

For 3 that's okay - the ultimate goal is to be able to ship everything as one in a single executable using pyinstaller anyway so same directory is fine.

**Comment by CaptainMeatloaf** [comment]
Done in #13
